name: Build All Platforms

on:
  workflow_dispatch:

jobs:
  desktop-build:
    uses: ./.github/workflows/build_desktop.yml 

  ios-build:
    uses: ./.github/workflows/ios_build.yml 

  android-build:
    uses: ./.github/workflows/android_build.yml
