name: Build PT-Framework for Desktop and Mobile

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, android, ios]
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.x
      
    - name: Download workloads
      run: |
        dotnet workload install android
        dotnet workload install ios

    - name: Restore dependencies
      run: |
        dotnet restore PT-Framework.sln

    - name: Publish build artifacts (Desktop)
      if: ${{ matrix.os == 'windows' || matrix.os == 'macos' }}
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        dotnet publish PT-Framework.csproj --configuration Release --framework net8.0 --output artifacts/publish/${{ matrix.os }}/ /p:Version=0.0.${{ github.run_number }}

    - name: Publish build artifacts (Mobile)
      if: ${{ matrix.os == 'ios' || matrix.os == 'android' }}
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        dotnet publish PT-Framework.csproj --configuration Release --framework net8.0-${{ matrix.os }} --output artifacts/publish/${{ matrix.os }}/ /p:Version=0.0.${{ github.run_number }}

    - name: Archive artifacts
      run: |
        mkdir -p ./releases
        zip -r ./releases/PT-Framework-${{ matrix.os }}.zip ./artifacts/publish/${{ matrix.os }}/
      
    - name: Upload artifacts to GitHub Actions
      uses: actions/upload-artifact@v4.6.0
      with:
          name: ${{ matrix.os }}-artifacts
          path: artifacts

    - name: Upload artifacts to GitHub Releases
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: ./releases/PT-Framework-${{ matrix.os }}.zip
        tag_name: testing-phase
        name: "Testing Phase Release for PT-Framework"
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  nuget-upload:
    runs-on: macos-latest
    needs: [build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.x

    - name: Download artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        path: artifacts
    
    - name: Organize files for NuGet package
      run: |
        mkdir -p nuget/lib/net8.0
        mkdir -p nuget/lib/net8.0-windows
        mkdir -p nuget/lib/net8.0-ios
        mkdir -p nuget/lib/net8.0-android

        Copy-Item -Path artifacts/windows-artifacts/* -Destination nuget/lib/net8.0/ -Recurse -Force
        Copy-Item -Path artifacts/macos-artifacts/* -Destination nuget/lib/net8.0/ -Recurse -Force
        Copy-Item -Path artifacts/windows-artifacts/* -Destination nuget/lib/net8.0-windows/ -Recurse -Force

        Copy-Item -Path artifacts/ios-artifacts/* -Destination nuget/lib/net8.0-ios/ -Recurse -Force
        Copy-Item -Path artifacts/android-artifacts/* -Destination nuget/lib/net8.0-android/ -Recurse -Force

    - name: Pack NuGet package
      run: |
        dotnet pack PT-Framework.csproj --no-build --output artifacts/nuget --include-symbols --include-source

    - name: Publish to NuGet
      run: |
        dotnet nuget push artifacts/nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

