name: Build PT-Framework for Desktop

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write
  discussions: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, linux]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.x
      
    - name: Restore dependencies
      run: |
        dotnet restore PT-Framework.csproj

    - name: Publish build artifacts
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          dotnet publish PT-Framework.csproj --configuration Release --framework net8.0 --runtime win-x64 --output artifacts/publish/windows/ /p:Version=0.0.${{ github.run_number }}
        elif [[ "${{ matrix.os }}" == "macos" ]]; then
          dotnet publish PT-Framework.csproj --configuration Release --framework net8.0 --runtime osx-x64 --output artifacts/publish/macos/ /p:Version=0.0.${{ github.run_number }}
        elif [[ "${{ matrix.os }}" == "linux" ]]; then
          dotnet publish PT-Framework.csproj --configuration Release --framework net8.0 --runtime linux-x64 --output artifacts/publish/linux/ /p:Version=0.0.${{ github.run_number }}
        fi

    - name: Archive artifacts
      run: |
        if [[ ! -d ./artifacts/publish/${{ matrix.os }}/ ]]; then
          echo "No artifacts found for ${{ matrix.os }}. Skipping."
          exit 1
        fi
        mkdir -p ./releases
        zip -r ./releases/PT-Framework-${{ matrix.os }}.zip ./artifacts/publish/${{ matrix.os }}/
      
    - name: Upload artifacts to GitHub Actions
      uses: actions/upload-artifact@v4.6.0
      with:
          name: ${{ matrix.os }}-artifacts
          path: artifacts

    - name: Upload artifacts to GitHub Releases
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: ./releases/PT-Framework-${{ matrix.os }}.zip
        tag_name: testing-phase
        name: "Testing Phase Release for PT-Framework"
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  nuget-upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.x

    - name: Download artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        path: artifacts
    
    - name: Organize files for NuGet package
      run: |
        mkdir -p nuget/lib/net8.0
        mkdir -p nuget/lib/net8.0-windows
        mkdir -p nuget/lib/net8.0-linux
        mkdir -p nuget/lib/net8.0-macos

        cp -r artifacts/publish/windows/* nuget/lib/net8.0-windows/
        cp -r artifacts/publish/linux/* nuget/lib/net8.0-linux/
        cp -r artifacts/publish/macos/* nuget/lib/net8.0-macos/

    - name: Pack NuGet package
      run: |
        dotnet pack PT-Framework.csproj --no-build --output artifacts/nuget --include-symbols --include-source

    - name: Publish to NuGet
      run: |
        dotnet nuget push artifacts/nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
